### PR TITLE
Fix bidi state leaking across layouts

### LINKED ISSUE #489: Bidi state is leaking between layouts
If you render RTL text and then render LTR text, the LTR text glyphs are in reverse order. Presumably, bidi state is leaking between layouts.

I.e., this test fails:

```rs
#[test]
fn glyph_order_rtl_then_ltr() {
    let mut env = TestEnv::new(test_name!(), None);

    // First, render some RTL text
    {
        let text = "مرحبا"; // Arabic "Hello"
        let builder = env.ranged_builder(text);
        let mut layout = builder.build(text);
        layout.break_all_lines(Some(200.0));
        layout.align(None, Alignment::Start, AlignmentOptions::default());

        assert!(layout.is_rtl());
    }

    // Now render LTR text - this shouldn't be affected by the previous RTL layout
    {
        let text = "ABC";
        let builder = env.ranged_builder(text);
        let mut layout = builder.build(text);
        layout.break_all_lines(Some(200.0));
        layout.align(None, Alignment::Start, AlignmentOptions::default());

        assert!(!layout.is_rtl());

        let line = layout.lines().next().unwrap();
        let item = line.items().next().unwrap();
        let glyph_run = match item {
            crate::PositionedLayoutItem::GlyphRun(glyph_run) => glyph_run,
            crate::PositionedLayoutItem::InlineBox(_) => unreachable!(),
        };

        assert!(!glyph_run.run().is_rtl());

        // For LTR text, positioned glyphs should have increasing x coordinates
        let positions: Vec<f32> = glyph_run.positioned_glyphs().map(|g| g.x).collect();
        for i in 1..positions.len() {
            assert!(
                positions[i] > positions[i - 1],
                "LTR positioned glyphs should have increasing x coordinates. Got: {:?}",
                positions
            );
        }
    }
}
```

### PR DESCRIPTION
**Pull request by taj-p**
Fixes #489 

Also consolidates regression tests to a separate file.

### CODE REVIEW

File: parley/src/context.rs [hunk 1]
```diff
@@ -151,6 +151,7 @@ impl<B: Brush> LayoutContext<B> {
         self.styles.clear();
         self.inline_boxes.clear();
         self.info.clear();
+        self.bidi.clear();
```
Comment (taj-p) [inline parley/src/context.rs:154]: This is how we fixed the bug.
